[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tosclib"
authors = [{name = "Alberto", email = "avq5ac1@gmail.com"}]
dynamic = ["version", "description"]
